### ISSUE TITLE
how to set padding around content?

### ISSUE THREAD

**Issue by Selecao** [bensonarafat/super_tooltip#82]
I see a default padding around content about 10 pixels, how to change that? I try for **overlayDimensions** and **bubbleDimensions** has no effect so.. Any suggestions guys?
Awesome package btw.

**Comment by kaiquegazola** [comment]
https://github.com/bensonarafat/super_tooltip/pull/81 has fixed this, but a new version has not yet been pushed to pub.dev.

Use the package as a git dependency until @bensonarafat publishes a new version:
```yaml
  super_tooltip:
    git:
      url: https://github.com/bensonarafat/super_tooltip.git
```
